WARNING 2023-02-22 11:43:47,437 django.request Bad Request: /api/instance/
WARNING 2023-02-22 11:44:07,653 django.request Bad Request: /api/instance/
WARNING 2023-02-22 11:44:12,180 django.request Bad Request: /api/instance/
WARNING 2023-02-22 11:44:40,756 django.request Bad Request: /api/instance/
WARNING 2023-02-22 11:48:42,622 django.request Bad Request: /api/instance/
WARNING 2023-02-22 11:51:33,924 django.request Bad Request: /api/instance/78ea3a37-25a4-4ec5-8171-fbc4b90cb7db/redisgraph/check-module-loaded/
ERROR 2023-02-22 11:51:42,676 redisinsight Unknown command error from redis instance:
Traceback (most recent call last):
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/redisai/views.py", line 40, in _wrapped_view
  File "./redisinsight/redisai/views.py", line 85, in models_view
  File "./redisinsight/redisai/services.py", line 181, in list_models
  File "./redisinsight/redisai/services.py", line 157, in _list_models
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'AI._MODELSCAN', with args beginning with: 
ERROR 2023-02-22 11:51:42,676 redisinsight Unknown command error from redis instance:
Traceback (most recent call last):
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/redisai/views.py", line 40, in _wrapped_view
  File "./redisinsight/redisai/views.py", line 224, in scripts_view
  File "./redisinsight/redisai/services.py", line 206, in list_scripts
  File "./redisinsight/redisai/services.py", line 185, in _list_scripts
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'AI._SCRIPTSCAN', with args beginning with: 
ERROR 2023-02-22 11:51:42,677 django.request Unknown Status Code: /api/instance/78ea3a37-25a4-4ec5-8171-fbc4b90cb7db/redisai/models/
ERROR 2023-02-22 11:51:42,681 django.request Unknown Status Code: /api/instance/78ea3a37-25a4-4ec5-8171-fbc4b90cb7db/redisai/scripts/
WARNING 2023-02-22 11:51:46,609 django.request Bad Request: /api/instance/78ea3a37-25a4-4ec5-8171-fbc4b90cb7db/redistimeseries/module-info/
WARNING 2023-02-22 11:51:47,789 django.request Bad Request: /api/instance/78ea3a37-25a4-4ec5-8171-fbc4b90cb7db/check-redisearch-module-loaded/
